### ISSUE TITLE
Does this work with Capistrano 3?

### ISSUE THREAD

**Issue by jmtame** [Druwerd/caplock#4]
When requiring caplock in the Capfile, I see this:

cap aborted!
NoMethodError: undefined method `plugin' for Capistrano:Module
Capfile:14:in`require'
Capfile:14:in `<top (required)>'

**Comment by nskitchgriddynamics** [comment]
I wished it worked in cap 3.0, but it does not.

```
NoMethodError: undefined method `plugin' for Capistrano:Module
/Users/nskitch/.gem/ruby/2.0.0/gems/caplock-0.3.1/lib/caplock.rb:79:in `<module:Caplock>'
```

**Comment by Lukom** [comment]
Extracted code from this gem and adapted for capistrano 3: [link](https://coderwall.com/p/mb-ppq/capistrano-deploy-lock)
